### JWT Authentication
# @name Token
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"fayis",
    "password":"3144"
}

### JWT Auth
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY5OTk3MTY2MCwiaWF0IjoxNjkyMTk1NjYwLCJqdGkiOiI0YzY5Y2U2YTdmNTk0ZjZhODNmY2NmY2I1ODU3Y2ZjMyIsInVzZXJfaWQiOjF9.oNOgR2xVIjZWBIQHYgSDKq4l5h1pwzrIPMFrzkMieEM"
}

###

###

# {
#     "name": "Test Website",
#     "url": "http://example.com/",
#     "description": "Test description",
#     "image": "",
#     "banners": "",
#     "category": [1, 2],
# }
